name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: dir

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyMuPDF Pillow python-docx PyYAML lxml pyinstaller

      - name: Build exe
        run: |
          pyinstaller --clean --onefile --name "合同重点提取工具" "新版.py"

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: 合同重点提取工具-windows
          path: dist/*.exe
